### ISSUE TITLE
Problems in backreference construction in regular expressions

### ISSUE THREAD

**Issue by Jokacer** [dotnet/docs.zh-cn#186]
In "What Backreferences match", in the explanation of the pattern "(?&lt;1&gt; a)(?&lt;1&gt; \ 1b)*" ，I think "(?&lt;1&gt;\1b)*" should match 1  value in group 1 instead of 0 or 1,is it right?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: e2fa77ea-67e4-d972-e6c4-9eff4203ce3e
* Version Independent ID: 266c2d26-307c-09df-05d0-3946e34fb448
* Content: [正则表达式中的反向引用构造](https://docs.microsoft.com/zh-cn/dotnet/standard/base-types/backreference-constructs-in-regular-expressions#numbered-backreferences)
* Content Source: [docs/standard/base-types/backreference-constructs-in-regular-expressions.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/standard/base-types/backreference-constructs-in-regular-expressions.md)
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by LisandroSu** [comment]
Issue moved to [dotnet/docs #7023](https://github.com/dotnet/docs/issues/7023) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Hello, @Jokacer , 
 
Your contribution is much appreciated. Your feedback is related to the original documentation. 
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/docs/issues/7023. 
 
We truly appreciate your contribution to our articles.  
 
Kind regards, 
Microsoft DOCS International Team
