### ISSUE TITLE
Exception!

### ISSUE THREAD

**Issue by 1277201882** [dotnet/docs.zh-cn#192]
In file ExpenseItHome.xaml.cs
InitializeComponent() is wrong and give me an exception.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: b0dc39f7-b153-a46c-3b88-07c8ed2c71bc
* Version Independent ID: 78a14535-9703-e2af-4451-783a7c4c10be
* Content: [在 Visual Studio 中创建一个 WPF 应用程序](https://docs.microsoft.com/zh-cn/dotnet/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application#style-data-with-data-templates)
* Content Source: [docs/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application.md)
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by imba-tjd** [comment]
I can't reproduce it.

**Comment by LisandroSu** [comment]
Issue moved to [dotnet/docs #7309](https://github.com/dotnet/docs/issues/7309) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Hello, @1277201882,

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/docs/issues/7309.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
