### ISSUE TITLE
The translated documents should be merged to docs.

### ISSUE THREAD

**Issue by sheng-jie** [dotnet/docs.zh-cn#210]
For this part (https://github.com/dotnet/docs.zh-cn/tree/live/docs/standard/microservices-architecture), I found it has been translated to the Chinese before in this website(https://www.azure.cn/zh-cn/campaigns/dotnet-application-architecture-ebooks/).
So why not sync that?

**Comment by CeciAc** [comment]
Hello, @sheng-jie
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @sheng-jie

Thank you for your feedback.  
Unfortunately, after reviewing your feedback our linguistic team considered it to be not fully aligned with our criteria for acceptance because it doesn't follow the correct protocol of new localized content which is out of our scope.

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.  
 
Kind regards, 

Microsoft DOCS International Team
