### ISSUE TITLE
The common style rules for translation.

### ISSUE THREAD

**Issue by yanxiaodi** [dotnet/docs.zh-cn#212]
I have submitted some feedback for Chinese translation but I am confused regarding the translation styles. For example:

For these keywords: DO, DO NOT, AVOID, CONSIDER, are they translatable? According to the feedback from Microsoft staffs, sometimes they should be translated: 
https://github.com/dotnet/docs.zh-cn/pull/173/commits/4639c5915e7b7ac3cef3a4a61aea31bcf1a3c9e1 
But sometimes they are not: 
https://github.com/dotnet/docs.zh-cn/pull/211/commits/36031d6e52457f67d457dffcd1320fb64d3b2280

For some English terms, should we add the blanks before and after them?
Sometimes Microsoft staff added the blanks like this: 
https://github.com/dotnet/docs.zh-cn/pull/173/commits/f28830c16f71caf2b0bb1eb9664ec79774063cf1

But sometimes the blanks are removed:
https://github.com/dotnet/docs.zh-cn/pull/211/commits/f3411f29003d6344170694c804e5e87cd7cf85cd

Do we have a uniform translation style? It would be better if Microsoft provides us with a guideline for translation. Thank you very much.

**Comment by LisandroSu** [comment]
Hello, @yanxiaodi 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello, @yanxiaodi
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hi @sara-nicolini @nokura while we are currently investigating and gathering info on this issue, do you have anything on your side about this that you can share with the end-user?

Thanks!

**Comment by mairaw** [comment]
Adding @JasonCard as well

**Comment by JasonCard** [comment]
Hi @LisandroSu, thank you for looping us in on this issue. Let's sync up on this internally. 
cc @Sara-Nicolini, @nokura, @mairaw

**Comment by CeciAc** [comment]
Hi team, 
adding a comment from our LM:
_These keywords seem to be an integral part of the localized sentence, and therefore I think they should be localized. As to the space question, there should be a space between an English word and a Chinese character according to Microsoft Styleguides; but some technical reasons may lead to inappropriate removal or insertion of spaces, for example, sometimes if a translator doesn’t know whether a placeholder will be replaced with Chinese or English, he or she may not be able to use spaces correctly._

**Comment by JasonCard** [comment]
Hello, @yanxiaodi

Thank you for your feedback.

Regarding those keywords, it is difficult to localize for some languages, so we previously reverted them back to English. However, we are currently re-evaluating how these keywords should be translated for each language. We will let you know once we have the approved translation for Simplified Chinese.

Regarding space question, please do add space between an English word and a Chinese character. For the case when those space were removed, please consider an exception due to technical issue.

Kind regards,
Microsoft DOCS International Team

**Comment by JasonCard** [comment]
Hi @yanxiaodi 

Regarding recommended translation of these keywords for Simplified Chinese, currently it's just a matter of preference, but you may use:
DO（务必：） / DO NOT（切忌：） / AVOID（避免：） / CONSIDER（考虑：）
We are working with writers to change the English sentence structure so it can be easily translated for all languages. Since we expect the English source to change soon, we will not have an official approved translation for these keywords for now. 

Kind regards,
Microsoft DOCS International Team
