### ISSUE TITLE
A translate error in zh-cn

### ISSUE THREAD

**Issue by usecompiled** [dotnet/docs.zh-cn#308]
[在此处输入反馈]
![image](https://user-images.githubusercontent.com/14042334/50536315-12316780-0b8e-11e9-9c6e-7bccd2d01552.png)
translate error:  “override” should be  translated as “重写”，not “重新”.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 6adc020a-0a39-b4e2-902a-c0d776356b2e
* Version Independent ID: ff107003-885e-0876-bbaa-2fb25daa6369
* Content: [override 修饰符 - C# 参考](https://docs.microsoft.com/zh-cn/dotnet/csharp/language-reference/keywords/override)
* Content Source: [docs/csharp/language-reference/keywords/override.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/language-reference/keywords/override.md)
* Product: **dotnet-csharp**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by LisandroSu** [comment]
Hello, @usecompiled 

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged.
Please review PR https://github.com/dotnet/docs.zh-cn/pull/310. For this reason we are closing this issue since it is duplicated.

Kind regards,
Microsoft DOCS International Team
