### ISSUE TITLE
Pull request ignored

### ISSUE THREAD

**Issue by NextTurn** [dotnet/docs.zh-cn#317]
PLEASE DO NOT IGNORE MY PULL REQUEST #297

**Comment by CeciAc** [comment]
Hello, @NextTurn 

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged.
Please review issue https://github.com/dotnet/docs.zh-cn/pull/297. For this reason we are closing this issue since it is duplicated.

Kind regards,
Microsoft DOCS International Team
