### ISSUE TITLE
Please add complete example for callback

### ISSUE THREAD

**Issue by miya898** [dotnet/docs.zh-cn#319]
On https://docs.microsoft.com/zh-cn/dotnet/standard/native-interop, can you also add the C/C++ code part in above examples for readers to better understand callback methods?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: bfe2d36f-8718-cf05-adf9-55725c959388
* Version Independent ID: df8f9d5d-816a-d285-b4d7-b3ba74aafd9a
* Content: [本机互操作性](https://docs.microsoft.com/zh-cn/dotnet/standard/native-interop)
* Content Source: [docs/standard/native-interop.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/standard/native-interop.md)
* Product: **dotnet**
* GitHub Login: @blackdwarf
* Microsoft Alias: **ronpet**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #9928](https://github.com/dotnet/docs/issues/9928) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @miya898 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/docs/issues/9928.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
