### ISSUE TITLE
Create a TileBrush and align its content to the bottom-right of its tile.

### ISSUE THREAD

**Issue by lienonegithub** [dotnet/docs.zh-cn#322]
bottomRightAlignedTileBrush.Stretch should be [Strech.Uniform]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 9aab7b5b-f348-ccbf-01cc-23b60ab063e3
* Version Independent ID: f28e8c3f-6e94-9025-18ec-dd7852be01c1
* Content: [如何：设置 TileBrush 的水平对齐方式和垂直对齐方式](https://docs.microsoft.com/zh-cn/dotnet/framework/wpf/graphics-multimedia/how-to-set-the-horizontal-and-vertical-alignment-of-a-tilebrush)
* Content Source: [docs/framework/wpf/graphics-multimedia/how-to-set-the-horizontal-and-vertical-alignment-of-a-tilebrush.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/framework/wpf/graphics-multimedia/how-to-set-the-horizontal-and-vertical-alignment-of-a-tilebrush.md)
* Product: **dotnet-framework**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #9997](https://github.com/dotnet/docs/issues/9997) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @lienonegithub 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/docs/issues/9997.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
