### ISSUE TITLE
string

### ISSUE THREAD

**Issue by FreeXiaoSuYu** [dotnet/docs.zh-cn#348]
能否出一个文档，从一个项目发布开始图文教学一下，其中需要下载的工具，工具如何部署，然后项目如何部署，再用个人感悟讲解这部分操作，不要用太多官方语言讲述，能出个这种图文教学吗。不能，也谢谢。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 06a17d5d-5f6e-d6bc-324b-af411a42ccb8
* Version Independent ID: f58588d7-70f6-aa32-5c6d-ac3e7d72d87c
* Content: [.NET Core 应用程序部署](https://docs.microsoft.com/zh-cn/dotnet/core/deploying/index#feedback)
* Content Source: [docs/core/deploying/index.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/core/deploying/index.md)
* Product: **dotnet-core**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #11306](https://github.com/dotnet/docs/issues/11306) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @FreeXiaoSuYu 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/docs/issues/11306

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
