### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by heyangmingUser** [dotnet/docs.zh-cn#357]
[在此处输入反馈]

dotnet add reference ../PrimeService/PrimeService.csproj
link:https://docs.microsoft.com/zh-cn/dotnet/core/testing/unit-testing-with-dotnet-test?toc=/aspnet/core/toc.json&bc=/aspnet/core/breadcrumb/toc.json&view=aspnetcore-2.2
Path format error,Please correct it
---

#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: e39c2f1b-f41a-bdf9-2646-09379941453d
* Version Independent ID: 422811cb-6287-03af-ba8d-1daebee9744d
* Content: [使用 dotnet test 和 xUnit 在 .NET Core 中进行 C# 代码单元测试](https://docs.microsoft.com/zh-cn/dotnet/core/testing/unit-testing-with-dotnet-test?toc=/aspnet/core/toc.json&bc=/aspnet/core/breadcrumb/toc.json&view=aspnetcore-3.0)
* Content Source: [docs/core/testing/unit-testing-with-dotnet-test.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/core/testing/unit-testing-with-dotnet-test.md)
* Product: **dotnet-core**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by imba-tjd** [comment]
没看出哪里error了。你想说要用反斜杠，不用斜杠？

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #11505](https://github.com/dotnet/docs/issues/11505) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @heyangmingUser 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/docs/issues/11505

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
