### ISSUE TITLE
Not sure is it a little typo

### ISSUE THREAD

**Issue by ArisLittle** [dotnet/docs.zh-cn#369]
Here is the sentence in this wonderful article: "This typically makes tests much easier to write and much faster to run when compared to running tests again the application's real infrastructure."

Does the "again" word really mean "against" ?
I'm not sure. If it is not a problem, please ignore my issue :)

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 1ebf17cd-9d3e-d928-0767-d06e346868bb
* Version Independent ID: 9e50c3eb-ea4b-0390-4b72-ae1dae2de4d3
* Content: [常用 Web 应用程序体系结构](https://docs.microsoft.com/zh-cn/dotnet/standard/modern-web-apps-azure-architecture/common-web-application-architectures)
* Content Source: [docs/standard/modern-web-apps-azure-architecture/common-web-application-architectures.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/standard/modern-web-apps-azure-architecture/common-web-application-architectures.md)
* Product: **dotnet**
* Technology: **dotnet-ebooks**
* GitHub Login: @ardalis
* Microsoft Alias: **wiwagn**

**Comment by CeciAc** [comment]
Hello, @ArisLittle

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/docs/pull/11725

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
