### ISSUE TITLE
The TaskCompletionSource not be canceled correct

### ISSUE THREAD

**Issue by voidweapon** [dotnet/docs.zh-cn#390]
In example of Exposing Complex EAP Operations As Tasks, the CancellationToken Just cancel WebClient, the tcs of TaskCompletionSource still running in some thread.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: a7a2d4f3-d369-9945-79d1-31efea2f06cc
* Version Independent ID: 3004dcc5-a1d4-ba57-102d-46d955548085
* Content: [TPL 和传统 .NET Framework 异步编程](https://docs.microsoft.com/zh-cn/dotnet/standard/parallel-programming/tpl-and-traditional-async-programming#feedback)
* Content Source: [docs/standard/parallel-programming/tpl-and-traditional-async-programming.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/standard/parallel-programming/tpl-and-traditional-async-programming.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #12519](https://github.com/dotnet/docs/issues/12519) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @voidweapon

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/docs/issues/12519

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
