### ISSUE TITLE
Lost the following code from HostSideView to Host

### ISSUE THREAD

**Issue by fbiwarning** [dotnet/docs.zh-cn#397]
This page do not contain the code about HostSideView HostSideAdapter AddIn and Host. 

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 0e6fd3c3-68eb-a164-f4cb-1ec07c7b233d
* Version Independent ID: da8b15c4-734d-6cc6-fa2d-5f26bb697164
* Content: [如何：创建作为 UI 的外接程序](https://docs.microsoft.com/zh-cn/dotnet/framework/wpf/app-development/how-to-create-an-add-in-that-is-a-ui#feedback)
* Content Source: [docs/framework/wpf/app-development/how-to-create-an-add-in-that-is-a-ui.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/framework/wpf/app-development/how-to-create-an-add-in-that-is-a-ui.md)
* Product: **dotnet-framework**
* Technology: **dotnet-wpf**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #12646](https://github.com/dotnet/docs/issues/12646) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @fbiwarning 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/docs/issues/12646
We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
