### ISSUE TITLE
class namespace change

### ISSUE THREAD

**Issue by AlbertChopin** [dotnet/docs.zh-cn#399]
remove using Microsoft.Data.DataView;

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: edace175-268c-7428-dad5-95cd974422c3
* Version Independent ID: 707aed84-b636-088a-bf57-1cc5e4f69631
* Content: [什么是 ML.NET 以及它如何工作？ - ML.NET](https://docs.microsoft.com/Zh-cn/dotnet/machine-learning/how-does-mldotnet-work#feedback)
* Content Source: [docs/machine-learning/how-does-mldotnet-work.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/machine-learning/how-does-mldotnet-work.md)
* Product: **dotnet-ml**
* GitHub Login: @natke
* Microsoft Alias: **nakersha**

**Comment by CeciAc** [comment]
Hello, @AlbertChopin 

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged.
Please review issue https://github.com/dotnet/docs/issues/12771 . For this reason we are closing this issue since it is duplicated.

Kind regards,
Microsoft DOCS International Team
