### ISSUE TITLE
txt problem

### ISSUE THREAD

**Issue by Thousandyearsofwar** [dotnet/docs.zh-cn#415]
[在此处输入反馈]

(?(n2)     | Test whether n2 was matched in the input string.

)\d{7}     | If n2 was matched, match seven decimal digits.

should be

(?(n2)    | Test whether n2 was matched in the input string.

\d{7}      | If n2 was matched, match seven decimal digits.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 3af3731f-af2c-e8e6-cb90-51311eb350fb
* Version Independent ID: 3c03bf87-5592-d816-5b86-5b34b6595e6f
* Content: [.NET 正则表达式中的备用构造](https://docs.microsoft.com/zh-cn/dotnet/standard/base-types/alternation-constructs-in-regular-expressions#feedback)
* Content Source: [docs/standard/base-types/alternation-constructs-in-regular-expressions.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/standard/base-types/alternation-constructs-in-regular-expressions.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by srvbpigh** [comment]
Hello, @Thousandyearsofwar
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #13442](https://github.com/dotnet/docs/issues/13442) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @Thousandyearsofwar

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/docs/issues/13442

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
