### ISSUE TITLE
Error CS1061 'List<string>' does not contain a definition for 'Changed' & “own goal” code

### ISSUE THREAD

**Issue by kinglionsz** [dotnet/docs.zh-cn#475]
pls see:

https://github.com/dotnet/docs/issues/14442

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 362f3e73-a902-45e6-382d-328a4552a235
* Version Independent ID: d4253465-4bfc-e473-f745-0d5e1ff4e76c
* Content: [介绍Introduction - C# language specification](https://docs.microsoft.com/zh-cn/dotnet/csharp/language-reference/language-specification/introduction#operators)
* Content Source: [spec/introduction.md](https://github.com/dotnet/csharplang.zh-cn/blob/live/spec/introduction.md)
* Product: **dotnet-csharp**
* Technology: **csharp-spec**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @kinglionsz
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @kinglionsz 

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged.
Please review issue https://github.com/dotnet/docs/issues/14442
For this reason we are closing this issue since it is duplicated.

Kind regards,
Microsoft DOCS International Team

**Comment by kinglionsz** [comment]
Please update this page.
Thanks.@CeciAc
