### ISSUE TITLE
GZip issue

### ISSUE THREAD

**Issue by he1a2s0** [dotnet/docs.zh-cn#503]
On my machine(Windows 10 + .NET Core 3.0), I have to replace 
```C#
 ... new HttpClient() ... 
```
with
```C#
... new HttpClient(new HttpClientHandler{ AutomaticDecompression = System.Net.DecompressionMethods.GZip }) ...
```
to make the sample code work properly.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 3aeee012-d49e-e096-229c-44d38063b34f
* Version Independent ID: 86f4283b-fd68-22b5-c546-afe3c554d434
* Content: [演练：创建数据流管道](https://docs.microsoft.com/zh-cn/dotnet/standard/parallel-programming/walkthrough-creating-a-dataflow-pipeline)
* Content Source: [docs/standard/parallel-programming/walkthrough-creating-a-dataflow-pipeline.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/standard/parallel-programming/walkthrough-creating-a-dataflow-pipeline.md)
* Product: **dotnet**
* Technology: **dotnet-standard**
* GitHub Login: @BillWagner
* Microsoft Alias: **dotnetcontent**

**Comment by srvbpigh** [comment]
Hello, @he1a2s0
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #16027](https://github.com/dotnet/docs/issues/16027) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @he1a2s0

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/docs/issues/16027

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
