### ISSUE TITLE
        Console.WriteLine($"x = {p.x}, y = {p,y}");  p,y is issue . you know should p.y

### ISSUE THREAD

**Issue by 62019** [dotnet/docs.zh-cn#510]
Console.WriteLine($"x = {p.x}, y = {p,y}");  p,y is issue . you know should p.y

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 38ac12d2-0496-d7df-491e-f75a0ff6beb5
* Version Independent ID: 6a8127dd-1d58-63e3-3963-685d9228f1ad
* Content: [public 关键字 - C# 参考](https://docs.microsoft.com/zh-cn/dotnet/csharp/language-reference/keywords/public#feedback)
* Content Source: [docs/csharp/language-reference/keywords/public.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/csharp/language-reference/keywords/public.md)
* Product: **dotnet-csharp**
* Technology: **csharp-language-reference**
* GitHub Login: @BillWagner
* Microsoft Alias: **wiwagn**

**Comment by srvbpigh** [comment]
Hello, @62019
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by imba-tjd** [comment]
dup of https://github.com/dotnet/docs/issues/16297

**Comment by CeciAc** [comment]
Hello, @62019 

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged.
Please review issuehttps://github.com/dotnet/docs/issues/16297 
For this reason we are closing this issue since it is duplicated.

Kind regards,
Microsoft DOCS International Team
