### ISSUE TITLE
PublishSingleFile can't run as windows service

### ISSUE THREAD

**Issue by cnzhnet** [dotnet/docs.zh-cn#569]
When I use PublishSingleFile mode to publish an application,  the application cann't run as Windows Service: method UseWindowsService() does not work

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: d458030b-3efb-197f-6ac7-9fd4e2296218
* Version Independent ID: 6d01409e-fca6-10a3-2def-13ce28c9b210
* Content: [.NET Core 3.0 的新增功能](https://docs.microsoft.com/zh-cn/dotnet/core/whats-new/dotnet-core-3-0#feedback)
* Content Source: [docs/core/whats-new/dotnet-core-3-0.md](https://github.com/dotnet/docs.zh-cn/blob/live/docs/core/whats-new/dotnet-core-3-0.md)
* Product: **dotnet-core**
* GitHub Login: @Thraka
* Microsoft Alias: **adegeo**

**Comment by srvbpigh** [comment]
Hello, @cnzhnet
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [dotnet/docs #18072](https://github.com/dotnet/docs/issues/18072) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @cnzhnet, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/dotnet/docs/issues/18072. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
