### ISSUE TITLE
翻译示例代码注释

### ISSUE THREAD

**Issue by liuxilu** [dotnet/docs.zh-cn#611]
显然，代码注释应该被翻译，中文文档里的英文注释大概算不得注释。我也没找到不得翻译注释的规范。
更激进地，变量名也应写为中文。诚然，在实际生产中可能有种种顾虑导致规范代码不使用中文，但是作为示例，使用中文变量名更能让人明白。这可能让很多人无法接受，因此，可能也就是在这讲讲……

如果你们同意，我就开始翻译

**Comment by srvbpigh** [comment]
Hello, @liuxilu
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@liuxilu
我们诚挚感谢你的评论，我们会努力改善你在 docs.microsoft.com 的使用体验。但是，为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？

**No URL**

顺祝商祺！
Microsoft DOCS 国际团队

**Comment by CeciAc** [comment]
Hello, @<contributor's GITHUB name>,

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged.
Please review issue #612 
For this reason we are closing this issue since it is duplicated.

Kind regards,
Microsoft DOCS International Team
